spring:
  application:
    name: SkinCareBooking
    base-url: ${APP_VERIFICATION_BASE_URL}
    security:
      jwt:
        access_token:
          secret: ${JWT_ACCESS_TOKEN_SECRET}
          expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
        refresh_token:
          secret: ${JWT_REFRESH_TOKEN_SECRET}
          expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_SENDER_HOST}
    port: 587
    username: ${MAIL_SENDER_EMAIL}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloudinary:
    url: ${CLOUDINARY_URL}
